module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        "primaryColor": "var(--primaryColor)",
        "labelGrey": "var(--labelGrey)",
        "lightWhite": "var(--lightWhite)",
        "lightDark": "var(--lightDark)",
        "placeholderGrey": "var(--placeholderGrey)",
        "borderHr": "var(--borderHr)",
        "textPrimary": "var(--textPrimary)",
        "cancelButtonBlackBg": "var(--cancelButtonBlackBg)",
        "cancelButtonGreyBorder": "var(--cancelButtonGreyBorder)",
        "buttonActiveBg": "var(--buttonActiveBg)",
        "menuText": "var(--menuText)",
        "menuhover": "var(--menuhover)",
        "logoutBtn": "var(--logoutBtn)",
        "descriptionGreyTwo": "var(--descriptionGreyTwo)",
        "buttonGreyBg": "var(--buttonGreyBg)",
        "transparentBlackBg": "var(--transparentBlackBg)",
        "leftamountbg": "var(--leftamountbg)",
        "leftamontBr": "var(--leftamontBr)",
        "searchBg": "var(--searchBg)",
        "searchBr": "var(--searchBr)",
        "tableheaderBlack": "var(--tableheaderBlack)",
        "tableheaderBorder": "var(--tableheaderBorder)",
        "coinListBg": "var(--coinListBg)",
        "coinListActive": "var(--coinListActive)",
        "coinBr": "var(--coinBr)",
        "nameCircle": "var(--nameCircle)",
        "rightincard": "var(--rightincard)",
        "summaryLabel": "var(--summaryLabel)",
        "summaryText": "var(--summaryText)",
        "summarytotalbr": "var(--summarytotalbr)",
        "rightincardBr": "var(--rightincardBr)",
        "tabletdBg": "var(--tabletdBg)",
        "tabletdBghover": "var(--tabletdBghover)",
        "signUpDarkBg": "var(--signUpDarkBg)",
        "screenBlackBg": "var(--screenBlackBg)",
        "textGrey": "var(--textGrey)",
        "loginGreyBorder": "var(--loginGreyBorder)",
        "modaltextbr": "var(--modaltextbr)",
        "modalcontText": "var(--modalcontText)",
        "numerBadge": "var(--numerBadge)",
        "btnDisabled": "var(--btnDisabled)",
        "uploadCard": "var(--uploadCard)",
        "greySupportedPlotforms": "var(--greySupportedPlotforms)",
        "textGreen": "var(--textGreen)",
        "textLightRed": "var(--textLightRed)",
        "amountBr": "var(--amountBr)",
        "textSkyblue": "var(--textSkyblue)",
        "darkyellowStatus": "var(--darkyellowStatus)",
        "permissionTopbr": "var(--permissionTopbr)",
        "cancelBtnHover": "var(--cancelBtnHover)",
        "textGray": "var(--textGray)",
        "bgOrange": "var(--bgOrange)",
        "cardBg": "var(--cardBg)",
        "cardBorder": "var(--cardBorder)",
        "requiredRed": "var(--requiredRed)",
        "addLabelBg": "var(--addLabelBg)",
        "amounttableHeader": "var(--amounttableHeader)",
        "kendoheader": "var(--kendoheader)",
        "kendoheadbr": "var(--kendoheadbr)",
        "kbodyrow": "var(--kbodyrow)",
        "kbodyrowbr": "var(--kbodyrowbr)",
        "kendotdBghover": "var(--kendotdBghover)",
        "kendotdBghoverBr": "var(--kendotdBghoverBr)",
        "kendofooter": "var(--kendofooter)",
        "kendofooterbr": "var(--kendofooterbr)",
        "kfooterarrow": "var(--kfooterarrow)",
        "kpagetrbg": "var(--kpagetrbg)",
        "kpagenum": "var(--kpagenum)",
        "tableInputBg": "var(--tableInputBg)",
        "scrollBar": "var(--scrollBar)",
        "referralbg": "var(--referralbg)",
        "referralborder": "var(--referralborder)",
        "lighttext": "var(--lighttext)",
        "errorBorderRed": "var(--errorBorderRed)",
        "tabbg": "var(--tabbg)",
        "tabActive": "var(--tabActive)",
        "tabcolor": "var(--tabcolor)",
        "profileTabActiveBg": "var(--profileTabActiveBg)",
        "profileBtn": "var(--profileBtn)",
        "amountBbr": "var(--amountBbr)",
        "getcodebr": "var(--getcodebr)",
        "labelborder": "var(--labelborder)",
        "notifPara": "var(--notifPara)",
        "errorpara": "var(--errorpara)",
        "profilehrbr": "var(--profilehrbr)",
        "profilesubtext": "var(--profilesubtext)",
        "blueBorder": "var(--blueBorder)",
        "textRed": "var(--textRed)",
        "textGray2": "var(--textGray2)",
        "closedStatus": "var(--closedStatus)",
        "textApproved": "var(--textApproved)",
        "textPending": "var(--textPending)",
        "textReject": "var(--textReject)",
        "textSubmit": "var(--textSubmit)",
        "inputDisabled": "var(--inputDisabled)",
        "secondaryBg": "var(--secondaryBg)",
        "greennotification": "var(--greennotification)",
        "logoutBtnHover": "var(--logoutBtnHover)",
        "qrcodeBg": "var(--qrcodeBg)",
        "overlayblack": "var(--overlayblack)",
        "registerLabelBg": "var(--registerLabelBg)",
        "errorBg": "var(--errorBg)",
        "warningBg": "var(--warningBg)",
        "infoBg": "var(--infoBg)",
        "partiallyPaid": "var(--partiallyPaid)",
        "kheadText": "var(--kheadText)",
        "referralBg": "var(--referralBg)",
        "referralBr": "var(--referralBr)",
        "StrokeColor": "var(--StrokeColor)",
        "dbkpiPara": "var(--dbkpiPara)",
        "dbkpiText": "var(--dbkpiText)",
        "dbkpiStroke": "var(--dbkpiStroke)",
        "titleColor": "var(--titleColor)",
        "kpcardhover": "var(--kpcardhover)",
        "tabletext": "var(--tabletext)",
        "inputfield": "var(--inputfield)",
        "feesviewborder": "var(--feesviewborder)",
        "membershipcardsbg": "var(--membershipcardsbg)",
        "membershiptextblue": "var(--membershiptextblue)",
        "membershipborder": "var(--membershipborder)",
        "membershiptextsilver": "var(--membershiptextsilver)",
        "membershipbordersilver": "var(--membershipbordersilver)",
        "membershipgoldtext": "var(--membershipgoldtext)",
        "membershiplightsilver": "var(--membershiplightsilver)",
        "membershipfreecardbg": "var(--membershipfreecardbg)",
        "membershipvaultsbg": "var(--membershipvaultsbg)",
        "membershiptableborder": "var(--membershiptableborder)",
        "browncolor": "var(--browncolor)",
        "deposisttablebr": "var(--deposisttablebr)",
        "topbr": "var(--topbr)",
        "advcard": "var(--advcard)",
        "membershiptopbr": "var(--membershiptopbr)",
        "paraColor": "var(--paraColor)",
        "subTextColor": "var(--subTextColor)",
        "BlackBg": "var(--BlackBg)",
        "sidedrawerBg": "var(--sidedrawerBg)",
        "defaultBadge": "var(--defaultBadge)",
        "radioBtn": "var(--radioBtn)",
        "Unfreezed": "var(--Unfreezed)",
        "FreezePending": "var(--FreezePending)",
        "UnfreezePending": "var(--UnfreezePending)",
        "UnderMaintenance": "var(--UnderMaintenance)",
        "Freezed": "var(--Freezed)",
        "leftlistHover": "var(--leftlistHover)",
        "pendingStatus": "var(--pendingStatus)",
        "cardbackground": "var(--cardbackground)",
        "tabsBg": "var(--tabsBg)",
        "bgblack": "var(--bgblack)",
        "cryptoline": "var( --cryptoline)",
        "Borderbr": "var( --Borderbr)",
        "inputBg": "var(--inputBg)",
        "notPaid": "var( --notPaid)",
        "paidApproved": "var( --paidApproved)",
        "canceled": "var( --canceled)",

      },
      backgroundImage: {
        "blueGradient": 'linear-gradient(90deg, rgba(64, 123, 255, 0.26) 0%, rgba(237, 243, 255, 0.26) 100%)',
        "greenGradient": 'linear-gradient(90deg, rgba(10, 202, 224, 0.26) 0%, rgba(237, 243, 255, 0.26) 100%)',
        "brownGradient": 'linear-gradient(90deg, rgba(229, 156, 133, 0.26) 0%, rgba(237, 243, 255, 0.26) 100%)',
        greenLightDarkGradiant: 'linear-gradient(95deg, rgba(31, 176, 66, 1) -1.86%, rgba(6, 52, 22, 1) 102.59%)',
        purpleBlueGradiant: 'linear-gradient(94deg, rgba(99, 118, 196, 1) 10.19%, rgba(56, 207, 237, 1) 112.27%)',
        redMerunGradiant: 'linear-gradient(95deg, rgba(255, 0, 0, 1) -1.86%, rgba(121, 20, 20, 1) 102.59%)',
        skyBlueGradient: 'linear-gradient(94deg, #6376C4 10.19%, #38CFED 112.27%)',
        yellowGradient: 'linear-gradient(90deg, rgba(215, 229, 133, 0.26) 0%, rgba(237, 243, 255, 0.26) 100%)',
        "darkpurple": 'linear-gradient(90deg, rgba(138, 35, 140, 1) 35%, rgba(242, 108, 244, 1) 100%)',
        //  'SuccessBg':"url('./src/assets/images/success-bg.svg')",
        'holdingBg': "ulr('./src/assets/images/holding_card.png)",
      },
      fontFamily: {
        IBMplex: ['Blinker, serif, IBM Plex Sans', 'sans-serif'],
        webIcons: ['WebComponentsIcons']
      },
      fontSize: {
        md: '22px',
        large: '28px',
        mediumfont: '26px',
        extralarge: '34px',
        xxxl: '40px',

      },
      borderRadius: {
        5: "5px",
      },
      height: {
        h42: "52px",
      },
      boxShadow: {
        'registerShadow': '0px 0px 4px 0px rgba(255, 255, 255, 0.25)',
        'cardShadow': 'box-shadow: 0px 0px 4px 0px rgba(0, 0, 0, 0.15);',
      },
    },
  },
  plugins: [tailwindcss,autoprefixer],
}; 